export const merch = {
    Shirt: [
        {
            id:1,
            name: "Hot white shirt for dudes",
            price: 10.99,
            rating: 4,
            image: "https://m.media-amazon.com/images/I/611t4nQtUxL._UY606_.jpg",
            about: "sdasdas!",
        },
        {
            id:2,
            name: "Basic white shirt for gifting ",
            price: 9.99,
            rating: 5,
            image: "https://m.media-amazon.com/images/I/611t4nQtUxL._UY606_.jpg",
            about: "web-heasdasdasad!",
        },
        {
            id:3,
            name: "Basic white for GriLs",
            price: 12.99,
            rating: 1,
            image: "https://5.imimg.com/data5/NM/LX/MY-42532489/mens-black-jacket-500x500.jpg",
            about: "asdasdasdasd? ",
        },
        {
            id:4,
            name: "Black shit for limited edition",
            price: 8.99,
            rating: 3,
            image: "https://5.imimg.com/data5/NL/SM/GLADMIN-3270310/black-shirt-500x500.png",
            about: "asdasdasfdfssdasdasfsdggrthjyjgbdfgdffsddfgd",
        },
        {
            id:5,
            name: "Custom T-shirt (event specific)",
            price: 12.33,
            image: "https://www.mydesignation.com/wp-content/uploads/2019/08/malayali-tshirt-mydesignation-mockup-image-latest-golden-.jpg",
            about: "sadasfsgnsjidksmjdsbndaskndjnmlasn",
        },
    ],
    Jacket: [
        {
            id:6,
            name: "Fluffly jacket for winters",
            price: 12.33,
            image: "https://5.imimg.com/data5/SELLER/Default/2020/10/CD/IZ/IY/12789060/mens-jackets-500x500.jpg",
            about: "asdasdsjsodaliwoejewopdsdsa",
        },
        {
            id:7,
            name: "Extra long jacket for boys",
            price: 12.33,
            image: "https://5.imimg.com/data5/BV/UY/ZP/SELLER-59756470/mens-cotton-jacket-500x500.jpg",
            about: "sadasfsgnsjidksmjdsbndaskndjnmlasn",
        },
        {
            id:8,
            name: "Thin jacket for summers",
            price: 12.33,
            image: "https://5.imimg.com/data5/NM/LX/MY-42532489/mens-black-jacket-500x500.jpg",
            about: "sadasfsgnsjidksmjdsbndaskndjnmlasn",
        },
        {
            id:9,
            name: "Comforter",
            price: 12.33,
            image: "https://5.imimg.com/data5/NM/LX/MY-42532489/mens-black-jacket-500x500.jpg",
            about: "sadasfsgnsjidksmjdsbndaskndjnmlasn",
        },
    ],
    Cap: [
        {
            id:10,
            name: "Snap-Back Blue for boys",
            price: 12.33,
            image: "https://5.imimg.com/data5/NM/LX/MY-42532489/mens-black-jacket-500x500.jpg",
            about: "askfsdnjksnksanjkasnd.",
        },
        {
            id:11,
            name: "Snap-back White for girls",
            price: 12.33,
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTT9jqnuZF0-7UI47wbQtsy3qcgyfGxXFQtGQ&usqp=CAU",
            about: "askfsdnjksnksanjkasndasdassdasdasf.",
        },
        {
            id:12,
            name: "cap",
            price: 12.33,
            image: "https://assets.ajio.com/medias/sys_master/root/20211013/NiBc/6166262baeb26901108e767c/puma__poly_cotton_cap_ind.jpg",
            about: "askfsdnjksnksanjkasndwqeqwhhjjgfnhfggf.",
        },
    ],
};
